title: Marketing Analytics
author: Franck Mortagne
email: franck.mortagne.us@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website stores a number of data science projects applied to marketing analytics and customer insights topics.

# social links
linkedIn_username: Franck Mortagne # DO NOT include the @ character, or else the build will fail!
github_username:  FMortagne # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
